# Generated by Django 6.0.5 on 2026-05-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_description_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение'),
        ),
    ]
